# Config file for automatic testing at travis-ci.com

dist: bionic
matrix:
  include:
    - language: python
      python:
        - 3.8
      before_install:
            - sudo apt-get update -qq
            - sudo apt-get install libev-dev
      install: pip install -U tox-travis
      script: tox

    - language: node_js
      node_js:
        - '8'
      before_install:
        - cd src/uvc_serviceportal/static/csc
      install:
        - yarn
      script:
        - yarn test
