server:
  host: 0.0.0.0
  port: 8090

SAML:
  folder: SAML

templates:
  eager: True
  cache: templates_cache
  debug: True

sessions:
  folder: sessions
  environ_key: hansegonpeter
  timeout: 3600

defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

app:
  auth_backend: http://api.novareto.de
  mq_url: amqp://guest:guest@localhost:5672//
