server:
  host: 0.0.0.0
  port: 8090

defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

app:
  auth_backend: http://api.novareto.de
  mq_url: amqp://guest:guest@localhost:5672//
